import { ListingCardProps } from "@/components/listings/ListingCard";

// Plant category taxonomy — maps to real plant families/types
export type PlantCategory =
  | "monstera"
  | "philodendron"
  | "ficus"
  | "anthurium"
  | "orchid"
  | "cactus-succulent"
  | "pothos-scindapsus"
  | "alocasia"
  | "calathea"
  | "fern"
  | "palm"
  | "bromeliad"
  | "rare-variegated"
  | "cutting"
  | "outdoor-garden"
  // Inventory categories
  | "pots-ceramic"
  | "pots-plastic"
  | "substrate-soil"
  | "fertilizer"
  | "tools-care"
  | "lighting-grow";

export interface ExtendedListingCardProps extends ListingCardProps {
  plantCategory?: PlantCategory;
}

export const SAMPLE_LISTINGS: ExtendedListingCardProps[] = [
  {
    id: "lst-1",
    title: "იშვიათი Monstera Thai Constellation (დიდი ზომა, ფესვიანი)",
    price: 180,
    itemType: "PLANT",
    plantCategory: "monstera",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "COURIER"],
    images: [
      "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545241047-6083a3684587?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (ვაკე)",
    lat: 41.7116,
    lng: 44.7554,
    isPremium: true,
    viewsCount: 142,
    seller: {
      id: "usr-1",
      fullName: "თამარ ბოტანიკა",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      rating: 4.9,
      totalReviews: 28,
      badges: ["Trusted Seller", "Green Thumb"],
      tier: "TIER_2",
      customSlug: "tamarbustan",
    },
  },
  {
    id: "lst-2",
    title: "Philodendron Pink Princess — კარგად გამოხატული ვარიეგაციით",
    price: 0,
    itemType: "PLANT",
    plantCategory: "philodendron",
    transactionType: "TRADE",
    deliveryMethods: ["PICKUP", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?w=800&auto=format&fit=crop&q=80",
    ],
    city: "ბათუმი",
    lat: 41.6423,
    lng: 41.6339,
    tradePreferences: ["Monstera Albo", "Anthurium", "Syngonium Red Spot"],
    viewsCount: 89,
    seller: {
      id: "usr-2",
      fullName: "გიორგი მცენარეები",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
      rating: 5.0,
      totalReviews: 14,
      badges: ["Swap Master", "Green Thumb"],
      tier: "TIER_1",
    },
  },
  {
    id: "lst-3",
    title: "პრემიუმ კერამიკული ქოთნების კომპლექტი სადგამით (3 ცალი)",
    price: 65,
    itemType: "INVENTORY",
    plantCategory: "pots-ceramic",
    transactionType: "NEGOTIABLE",
    deliveryMethods: ["PICKUP", "COURIER", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (საბურთალო)",
    lat: 41.7271,
    lng: 44.7742,
    isPremium: true,
    viewsCount: 65,
    seller: {
      id: "usr-3",
      fullName: "Ceramica Botanica",
      avatarUrl: "",
      rating: 4.8,
      totalReviews: 42,
      badges: ["Trusted Seller"],
      tier: "TIER_2",
      customSlug: "ceramica",
    },
  },
  {
    id: "lst-4",
    title: "Ficus Lyrata (ვიოლინოსებრი ფიკუსი, სიმაღლე 1.2 მ)",
    price: 110,
    itemType: "PLANT",
    plantCategory: "ficus",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "COURIER"],
    images: [
      "https://images.unsplash.com/photo-1545241047-6083a3684587?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&auto=format&fit=crop&q=80",
    ],
    city: "ქუთაისი",
    viewsCount: 112,
    seller: {
      id: "usr-4",
      fullName: "Green Corner Kutaisi",
      avatarUrl: "",
      rating: 4.7,
      totalReviews: 9,
      badges: ["Green Thumb"],
      tier: "FREE",
    },
  },
  {
    id: "lst-5",
    title: "სპეციალური აროიდების სუბსტრატი (ქერქი + პერლიტი + ნახშირი) 10ლ",
    price: 25,
    itemType: "INVENTORY",
    plantCategory: "substrate-soil",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "COURIER", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (დიდუბე)",
    viewsCount: 204,
    seller: {
      id: "usr-1",
      fullName: "თამარ ბოტანიკა",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      rating: 4.9,
      totalReviews: 28,
      badges: ["Trusted Seller", "Green Thumb"],
      tier: "TIER_2",
      customSlug: "tamarbustan",
    },
  },
  {
    id: "lst-6",
    title: "Anthurium Clarinervium (ხავერდოვანი ფოთლებით, ახალი ფესვებით)",
    price: 75,
    itemType: "PLANT",
    plantCategory: "anthurium",
    transactionType: "NEGOTIABLE",
    deliveryMethods: ["PICKUP", "COURIER"],
    images: [
      "https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (ჩუღურეთი)",
    viewsCount: 78,
    seller: {
      id: "usr-5",
      fullName: "სალომე მწვანე",
      avatarUrl: "",
      rating: 5.0,
      totalReviews: 6,
      badges: ["Green Thumb"],
      tier: "FREE",
    },
  },
  {
    id: "lst-7",
    title: "Monstera Deliciosa (ვარიეგატი, 3 ფოთოლი)",
    price: 95,
    itemType: "PLANT",
    plantCategory: "monstera",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP"],
    images: [
      "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (ისანი)",
    viewsCount: 201,
    seller: {
      id: "usr-6",
      fullName: "ნინო ჯუნგლი",
      avatarUrl: "",
      rating: 4.6,
      totalReviews: 11,
      badges: ["Green Thumb"],
      tier: "TIER_1",
    },
  },
  {
    id: "lst-8",
    title: "Alocasia Zebrina (სრულ ზომამდე გამოზრდილი)",
    price: 55,
    itemType: "PLANT",
    plantCategory: "alocasia",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?w=800&auto=format&fit=crop&q=80",
    ],
    city: "ბათუმი",
    viewsCount: 44,
    seller: {
      id: "usr-7",
      fullName: "ლევან ტროპიკული",
      avatarUrl: "",
      rating: 4.5,
      totalReviews: 3,
      badges: [],
      tier: "FREE",
    },
  },
  {
    id: "lst-9",
    title: "Calathea Orbifolia (3 ფოთოლი, ამოყვავებული)",
    price: 0,
    itemType: "PLANT",
    plantCategory: "calathea",
    transactionType: "TRADE",
    deliveryMethods: ["PICKUP"],
    images: [
      "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (გლდანი)",
    tradePreferences: ["Monstera", "Pothos Njoy"],
    viewsCount: 33,
    seller: {
      id: "usr-8",
      fullName: "მარიამ ბოტანიკა",
      avatarUrl: "",
      rating: 0,
      totalReviews: 0,
      badges: [],
      tier: "FREE",
    },
  },
  {
    id: "lst-10",
    title: "Phalaenopsis ორქიდეა — 2 ტოტი, 12 კვირტი (ვარდისფერი)",
    price: 45,
    itemType: "PLANT",
    plantCategory: "orchid",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "COURIER"],
    images: [
      "https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (ვაკე)",
    viewsCount: 87,
    seller: {
      id: "usr-9",
      fullName: "ეკა ყვავილი",
      avatarUrl: "",
      rating: 5.0,
      totalReviews: 7,
      badges: ["Trusted Seller"],
      tier: "TIER_1",
    },
  },
  {
    id: "lst-11",
    title: "კაქტუსების კოლექცია 5 სხვადასხვა სახეობა (Echinocactus, Gymnocalycium)",
    price: 40,
    itemType: "PLANT",
    plantCategory: "cactus-succulent",
    transactionType: "NEGOTIABLE",
    deliveryMethods: ["PICKUP", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&auto=format&fit=crop&q=80",
    ],
    city: "ქუთაისი",
    viewsCount: 56,
    seller: {
      id: "usr-4",
      fullName: "Green Corner Kutaisi",
      avatarUrl: "",
      rating: 4.7,
      totalReviews: 9,
      badges: ["Green Thumb"],
      tier: "FREE",
    },
  },
  {
    id: "lst-12",
    title: "Pothos Njoy კალმები (5 ცალი, ფესვიანი) — ადვილი მოვლა",
    price: 15,
    itemType: "PLANT",
    plantCategory: "pothos-scindapsus",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "COURIER", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&auto=format&fit=crop&q=80",
    ],
    city: "რუსთავი",
    viewsCount: 120,
    seller: {
      id: "usr-10",
      fullName: "ანა მცენარე",
      avatarUrl: "",
      rating: 4.9,
      totalReviews: 18,
      badges: ["Green Thumb"],
      tier: "TIER_1",
    },
  },
  {
    id: "lst-13",
    title: "LED Grow Light — ნათება მცენარეებისთვის 45W, Full Spectrum",
    price: 89,
    itemType: "INVENTORY",
    plantCategory: "lighting-grow",
    transactionType: "FIXED",
    deliveryMethods: ["COURIER", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (საბურთალო)",
    viewsCount: 95,
    seller: {
      id: "usr-3",
      fullName: "Ceramica Botanica",
      avatarUrl: "",
      rating: 4.8,
      totalReviews: 42,
      badges: ["Trusted Seller"],
      tier: "TIER_2",
      customSlug: "ceramica",
    },
  },
  {
    id: "lst-14",
    title: "Philodendron Gloriosum — ნელა მზარდი, ხავერდოვანი ფოთოლი",
    price: 0,
    itemType: "PLANT",
    plantCategory: "philodendron",
    transactionType: "TRADE",
    deliveryMethods: ["PICKUP"],
    images: [
      "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (მთაწმინდა)",
    tradePreferences: ["Anthurium Crystallinum", "Hoya"],
    viewsCount: 67,
    seller: {
      id: "usr-11",
      fullName: "ირა ბოტ.",
      avatarUrl: "",
      rating: 4.8,
      totalReviews: 5,
      badges: ["Green Thumb"],
      tier: "FREE",
    },
  },
  {
    id: "lst-15",
    title: "თხევადი სასუქი აროიდებისთვის (NPK 5-5-5 + Mg, Fe) — 500 მლ",
    price: 18,
    itemType: "INVENTORY",
    plantCategory: "fertilizer",
    transactionType: "FIXED",
    deliveryMethods: ["PICKUP", "COURIER", "MARSHRUTKA"],
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (დიდუბე)",
    viewsCount: 149,
    seller: {
      id: "usr-1",
      fullName: "თამარ ბოტანიკა",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
      rating: 4.9,
      totalReviews: 28,
      badges: ["Trusted Seller", "Green Thumb"],
      tier: "TIER_2",
      customSlug: "tamarbustan",
    },
  },
  {
    id: "lst-16",
    title: "🎁 საჩუქარი: Pothos და დაფესვიანებული მონსტერას კალმები",
    price: 0,
    itemType: "PLANT",
    plantCategory: "pothos-scindapsus",
    transactionType: "GIFT",
    deliveryMethods: ["PICKUP"],
    images: [
      "https://images.unsplash.com/photo-1596724805735-a1309fef5163?w=800&auto=format&fit=crop&q=80",
    ],
    city: "თბილისი (საბურთალო)",
    lat: 41.7289,
    lng: 44.7648,
    viewsCount: 210,
    seller: {
      id: "usr-4",
      fullName: "გიორგი მ.",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
      rating: 5.0,
      totalReviews: 12,
      badges: ["Trusted Seller"],
      tier: "FREE",
    },
  },
];
